### ISSUE TITLE
Error java.lang.NoClassDefFoundError: ETSqliteOpenHelper

### ISSUE THREAD

**Issue by phantomis** [ExactTarget/JB4A-SDK-Android#3]
Loading the lib on the app I'm receiving this error : 
```
art  I  Rejecting re-init on previously-failed class java.lang.Class<com.exacttarget.etpushsdk.data.ETSqliteOpenHelper>
art  I  Rejecting re-init on previously-failed class java.lang.Class<com.exacttarget.etpushsdk.data.ETSqliteOpenHelper>
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/exacttarget/etpushsdk/data/ETSqliteOpenHelper;
 	at com.exacttarget.etpushsdk.ETPush.sendRegistration(ETPush.java:836)
 	at com.exacttarget.etpushsdk.ETPush.registerDeviceToken(ETPush.java:791)
 	at com.exacttarget.etpushsdk.ET_GenericReceiver.onReceive(ET_GenericReceiver.java:140)
 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2579)
 	at android.app.ActivityThread.access$1700(ActivityThread.java:144)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:135)
 	at android.app.ActivityThread.main(ActivityThread.java:5221)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/AndroidRuntime(18055): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.exacttarget.etpushsdk.data.ETSqliteOpenHelper" on path: DexPathList[[zip file "/data/app/com.cmr.activities-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 	... 13 more
 	Suppressed: java.lang.NoClassDefFoundError: com.exacttarget.etpushsdk.data.ETSqliteOpenHelper
 		at dalvik.system.DexFile.defineClassNative(Native Method)
 		at dalvik.system.DexFile.defineClass(DexFile.java:226)
 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
 		at dalvik.system.DexPathList.findClass(DexPathList.java:321)
 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
 		... 15 more
 	Suppressed: java.lang.ClassNotFoundException: com.exacttarget.etpushsdk.data.ETSqliteOpenHelper
 		at java.lang.Class.classForName(Native Method)
 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 		... 14 more
 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

Tested on Android Lollipop 5.0 ART and library 3.4.1

**Comment by et-bmote** [comment]
Glad to help you out.  It would appear that you have a configuration problem in your setup.  Please double check your setup against the documentation and open a support ticket if your problem persists.

**Comment by phantomis** [comment]
The same code works on Android 4.0.4 , I think isn't a configuration problem

**Comment by et-bmote** [comment]
We thoroughly test with automated tools and nothing gets into production without going through our Quality Engineers.  I can assure you we have tested on every supported version of Android including Android 5.0.  Dalvik is no longer an option as ART is the only runtime available as of 5.0.  Please open a support ticket so we can help you further.

**Comment by androidfu** [comment]
This issue has had no active for more than 60 days.  Considered closed unless there is further comment.
